### PR TITLE
Add HtmlAttributes and SvgAttributes

### PR DESCRIPTION
**Pull request by milesj**
Implements https://github.com/frenic/csstype/issues/59

Added all data from `mdn-browser-compat-data` that I could find. However, did not find anything for `aria-*` attributes, maybe https://www.npmjs.com/package/aria-attributes or https://www.npmjs.com/package/aria-data?

@frenic

### CODE REVIEW

**Comment by frenic** [comment]
This looks promising! Thank you. I'll have a closer look as soon as I can.

Do you think `aria-*` attributes are relevant for styling purposes?

**Comment by milesj** [comment]
@frenic Good point, probably not.

**Comment by milesj** [comment]
@frenic Holiday bump.

**Comment by milesj** [comment]
Awesome, thank you!

**Pull request merged**
